bitstring.diff

diff --git a/config/configure.in b/config/configure.in
--- a/config/configure.in
+++ b/config/configure.in
@@ -609,6 +609,7 @@ if test "$OCAMLC" = "$LOCAL_OCAML"/ocamlc.opt ; then
   OCAMLLEX=$LOCAL_OCAML/ocamllex.opt
   OCAMLYACC=$LOCAL_OCAML/ocamlyacc
   CAMLP4=$LOCAL_OCAML/camlp4
+  CAMLP4OF=$LOCAL_OCAML/camlp4of.opt
 else
   if test "$OCAMLC" = "$LOCAL_OCAML"/ocamlc ; then
   OCAML_PATH="$LOCAL_OCAML"/
@@ -623,6 +624,7 @@ else
   OCAMLLEX=$LOCAL_OCAML/ocamllex
   OCAMLYACC=$LOCAL_OCAML/ocamlyacc
   CAMLP4=$LOCAL_OCAML/camlp4
+  CAMLP4OF=$LOCAL_OCAML/camlp4of
   else
   AC_CHECK_PROG(OCAMLOPT, ocamlopt.opt, ocamlopt.opt)
   AC_CHECK_PROG(OCAMLOPT, ocamlopt, ocamlopt, no)
@@ -633,6 +635,8 @@ else
   AC_CHECK_PROG(OCAMLDOC, ocamldoc, ocamldoc)
   AC_CHECK_PROG(OCAMLMKTOP, ocamlmktop, ocamlmktop)
   AC_CHECK_PROG(CAMLP4, camlp4, camlp4)
+  AC_CHECK_PROG(CAMLP4OF, camlp4of.opt, camlp4of.opt)
+  AC_CHECK_PROG(CAMLP4OF, camlp4of, camlp4of, no)
 fi
 fi
 
@@ -702,6 +706,17 @@ ifelse(AC_ACVERSION, [2.13], [],
    AC_SYS_LARGEFILE
 
 ])
+
+dnl Check for native endianness.
+AC_C_BIGENDIAN(,,
+  [AC_MSG_ERROR([Machine endianness could not be determined])]
+)
+if test "x$WORDS_BIGENDIAN" = "x"; then
+  NATIVEENDIAN=LittleEndian
+else
+  NATIVEENDIAN=BigEndian
+fi
+AC_SUBST(NATIVEENDIAN)
 
 # various header files
 AC_CHECK_FUNCS(setrlimit getrlimit strerror_r strerror posix_fallocate)
@@ -1361,6 +1376,7 @@ AC_SUBST(OCAMLYACC)
 AC_SUBST(OCAMLDEP)
 AC_SUBST(OCAMLDEP_OPTIONS)
 AC_SUBST(CAMLP4)
+AC_SUBST(CAMLP4OF)
 AC_SUBST(PERL)
 AC_SUBST(OCAMLDOC)
 AC_SUBST(OCAMLMKTOP)
@@ -1431,6 +1447,7 @@ AC_OUTPUT(\
   Makefile.config \
   mldonkey.rc \
   $AUTOCONF.new $GTK_AUTOCONF.new \
+   ../src/utils/bitstring/bitstring.ml \
    ../src/utils/lib/magic.ml \
    ../src/networks/donkey/donkeySui.ml \
    ../src/daemon/driver/driverGraphics.ml \
@@ -1443,7 +1460,8 @@ diff $GTK_AUTOCONF.new $GTK_AUTOCONF 2> /dev/null > /dev/null || cp -f $GTK_AUTO
 cd ..
 
 echo -e "\nBuilding dependencies (if it blocks, try '$GNU_MAKE depend' to see the problem)"
-$GNU_MAKE depend 2> /dev/null > /dev/null || echo "Building dependencies fails: try: '$GNU_MAKE depend'"
+#$GNU_MAKE depend 2> /dev/null > /dev/null || echo "Building dependencies fails: try: '$GNU_MAKE depend'"
+$GNU_MAKE depend
 
 echo -e -n "\nConfiguring MLDonkey" $MLDONKEY_VERSION
 if test ! -z "$SCM_VERSION"; then
