-

diff --git a/config/configure b/config/configure
--- a/config/configure
+++ b/config/configure
@@ -1293,7 +1293,7 @@ MYCONFIG_ARGS_DEFINED=yes
 echo $MYCONFIG_ARGS
 
 CURRENT_VERSION=2.5
-CURRENT_RELEASE=18
+CURRENT_RELEASE=19
 
 REQUIRED_OCAML=3.07
 DOWNLOAD_OCAML=3.07pl2
@@ -9882,6 +9882,27 @@ echo "$as_me:$LINENO: result: $ac_cv_file____src_spider_spiderMain_ml" >&5
 echo "${ECHO_T}$ac_cv_file____src_spider_spiderMain_ml" >&6
 if test $ac_cv_file____src_spider_spiderMain_ml = yes; then
   EXTRA_DIRS="$EXTRA_DIRS src/spider"
+fi
+
+echo "$as_me:$LINENO: checking for ../src/btview/btviewMain.ml" >&5
+echo $ECHO_N "checking for ../src/btview/btviewMain.ml... $ECHO_C" >&6
+if test "${ac_cv_file____src_btview_btviewMain_ml+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  test "$cross_compiling" = yes &&
+  { { echo "$as_me:$LINENO: error: cannot check for file existence when cross compiling" >&5
+echo "$as_me: error: cannot check for file existence when cross compiling" >&2;}
+   { (exit 1); exit 1; }; }
+if test -r "../src/btview/btviewMain.ml"; then
+  ac_cv_file____src_btview_btviewMain_ml=yes
+else
+  ac_cv_file____src_btview_btviewMain_ml=no
+fi
+fi
+echo "$as_me:$LINENO: result: $ac_cv_file____src_btview_btviewMain_ml" >&5
+echo "${ECHO_T}$ac_cv_file____src_btview_btviewMain_ml" >&6
+if test $ac_cv_file____src_btview_btviewMain_ml = yes; then
+  EXTRA_DIRS="$EXTRA_DIRS src/btview"
 fi
 
 
