raise minimum OCaml version to 4.02.3

diff --git a/config/configure.in b/config/configure.in
--- a/config/configure.in
+++ b/config/configure.in
@@ -307,7 +307,7 @@ if test ! -z "$SUB_VERSION3"; then
   MLDONKEY_VERSION=$MLDONKEY_VERSION.$SUB_VERSION3
 fi
 
-MINIMUM_OCAML=3.12.0
+MINIMUM_OCAML=4.02.3
 DEFAULT_OCAML=4.08.0
 REQUIRED_OCAML=$DEFAULT_OCAML
 
@@ -587,23 +587,16 @@ if [ test -z "$OCAMLC" ] || [ test -z "$CAMLP4" ]; then
    BUILD_OCAML=yes
 else
   OCAMLVERSION=`$OCAMLC -v | sed -n -e 's|.*version* *\(.*\)$|\1|p' `
-  case "$OCAMLVERSION" in
-    "$REQUIRED_OCAML"*|4.*|3.12.*)
-        # ocaml version satisfied
-        ;;
-    *)
-        echo "Detected OCaml $OCAMLVERSION, required at least $MINIMUM_OCAML, need build"
-        BUILD_OCAML=yes
-        ;;
-  esac
-fi
-case "$REQUIRED_OCAML" in
-  3.11.*|3.10.*|3.0*)
-    echo "OCaml $REQUIRED_OCAML is too old, need build"
-    REQUIRED_OCAML=$DEFAULT_OCAML
+  if test "$OCAMLVERSION" \< "$MINIMUM_OCAML"; then
+    echo "Detected OCaml $OCAMLVERSION, required at least $MINIMUM_OCAML, need build"
     BUILD_OCAML=yes
-    ;;
-esac
+  fi
+fi
+if test "$REQUIRED_OCAML" \< "$MINIMUM_OCAML"; then
+  echo "OCaml $REQUIRED_OCAML is too old, need build"
+  REQUIRED_OCAML=$DEFAULT_OCAML
+  BUILD_OCAML=yes
+fi
 if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
 
   if [ test "$SYSTEM" = "mingw" ]; then
@@ -746,19 +739,11 @@ if test -f $OCAMLLIB/dynlink.cmxa; then
 fi
 
 # force usage of supported OCaml versions
-case "$OCAMLVERSION" in
-    3.12*|4.*) ;;
-    *)
-      echo "******** OCaml version >= $MINIMUM_OCAML required  *********" 1>&2;
-      echo "*******  Check http://ocaml.org/  ********" 1>&2;
-      exit 1
-      ;;
-esac
-
-case "$OCAMLVERSION" in
-  3.*|4.00*|4.01*|4.02*) ;;
-  *) OCAMLC="$OCAMLC -unsafe-string" ;;
-esac
+if test "$OCAMLVERSION" \< "$MINIMUM_OCAML"; then
+  echo "******** OCaml version >= $MINIMUM_OCAML required  *********" 1>&2;
+  echo "*******  Check http://ocaml.org/  ********" 1>&2;
+  exit 1
+fi
 
 if test "$OCAMLOPT" = "no"; then
   TARGET_TYPE=byte
@@ -773,11 +758,6 @@ else
     echo "******** Expected ocamlopt version $OCAMLVERSION , but got $OCAMLOPTVERSION *********" 1>&2;
     echo "*******  Check http://ocaml.org/  ********" 1>&2;
     exit 1; }
-
-  case "$OCAMLVERSION" in
-    3.*|4.00*|4.01*|4.02*) ;;
-    *) OCAMLOPT="$OCAMLOPT -unsafe-string" ;;
-  esac
 
 fi
 
@@ -801,10 +781,7 @@ if test "$DEBUG" = "yes"; then
 fi
 
 if test "$DEV" = "yes"; then
-  case "$OCAMLVERSION" in
-    3.*) DEVFLAGS="-annot" ;;
-    *) DEVFLAGS="-annot -bin-annot" ;;
-  esac
+  DEVFLAGS="-annot -bin-annot"
 fi
 
 echo ""
