configure: improve local ocaml build step
prefer modern ocaml when building locally
do not allow chosing svn ocaml version

diff --git a/config/configure.in b/config/configure.in
--- a/config/configure.in
+++ b/config/configure.in
@@ -307,9 +307,9 @@ if test ! -z "$SUB_VERSION3"; then
   MLDONKEY_VERSION=$MLDONKEY_VERSION.$SUB_VERSION3
 fi
 
-REQUIRED_OCAML=3.12.0
-DOWNLOAD_OCAML_MAJOR=3.12
-DOWNLOAD_OCAML=3.12.0
+MINIMUM_OCAML=3.12.0
+DEFAULT_OCAML=4.08.0
+REQUIRED_OCAML=$DEFAULT_OCAML
 
 REQUIRED_LABLGTK=1.2.7
 
@@ -435,7 +435,7 @@ AC_ARG_ENABLE(force-ocaml,
   AS_HELP_STRING([--enable-force-ocaml], [force usage of self-compiled OCaml]),
   [FORCE_OCAML="$enableval"])
 AC_ARG_ENABLE(ocamlver,
-  AS_HELP_STRING([--enable-ocamlver=VER], [force usage of specific OCaml version (3.10.1|SVN), ]),
+  AS_HELP_STRING([--enable-ocamlver=VER], [force usage of specific OCaml version]),
   [REQUIRED_OCAML="$enableval"])
 AC_ARG_ENABLE(mingw,
   AS_HELP_STRING([--enable-mingw], [force compilation with MINGW on Cygwin]),
@@ -583,87 +583,76 @@ AC_CHECK_TOOL(OCAMLC,ocamlc,ocamlrun ocamlc)
 AC_PATH_PROG(CAMLP4, camlp4,"",[$LOCAL_DIR/bin:$PATH])
 
 BUILD_OCAML=no
-if [ test -z "$OCAMLC" ] || [ test -z "$CAMLP4" ] || [ test "$REQUIRED_OCAML" = "SVN" ]; then
+if [ test -z "$OCAMLC" ] || [ test -z "$CAMLP4" ]; then
    BUILD_OCAML=yes
 else
   OCAMLVERSION=`$OCAMLC -v | sed -n -e 's|.*version* *\(.*\)$|\1|p' `
   case "$OCAMLVERSION" in
-    "$REQUIRED_OCAML"*|4.*|3.12.*|3.11.*|3.10.1*|3.10.2*) ;;
+    "$REQUIRED_OCAML"*|4.*|3.12.*)
+        # ocaml version satisfied
+        ;;
     *)
-        echo "Need build"
+        echo "Detected OCaml $OCAMLVERSION, required at least $MINIMUM_OCAML, need build"
         BUILD_OCAML=yes
         ;;
   esac
 fi
 case "$REQUIRED_OCAML" in
-  3.10.0|3.0*)
-    echo "Need build"
-    REQUIRED_OCAML=3.12.0
+  3.11.*|3.10.*|3.0*)
+    echo "OCaml $REQUIRED_OCAML is too old, need build"
+    REQUIRED_OCAML=$DEFAULT_OCAML
     BUILD_OCAML=yes
     ;;
 esac
 if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
 
   if [ test "$SYSTEM" = "mingw" ]; then
-    echo "********         Objective-Caml $REQUIRED_OCAML is required               *********" 1>&2;
-    echo "********     no valid OCaml compiler found on your system        *********" 1>&2;
-    echo "********   on MinGW there is no possibility to let configure     *********" 1>&2;
+    echo "********     No valid OCaml compiler found on your system.       *********" 1>&2;
+    echo "********    OCaml version >= $MINIMUM_OCAML is required.        *********" 1>&2;
+    echo "********   On MinGW there is no possibility to let configure     *********" 1>&2;
     echo "********   build the OCaml compiler with the included script     *********" 1>&2;
     echo "********    check http://mldonkey.sourceforge.net/Windows        *********" 1>&2;
     echo "********   for instuctions how to compile OCaml under MinGW      *********" 1>&2;
     exit 1
-  else  
-    
-  echo "********  Objective-Caml $REQUIRED_OCAML is required  *********" 1>&2;
-  if [ test "$WGET" = "" ] && [ test "$REQUIRED_OCAML" != "SVN" ]; then
+  else
+
+  echo "********  OCaml (and camlp4) version >= $MINIMUM_OCAML required  *********" 1>&2;
+  if [ test "$WGET" = "" ]; then
     echo "********          wget is missing          *********" 1>&2;
     echo "********       cannot download OCaml       *********" 1>&2;
     exit 1
   fi
-  echo "*******  Check http://caml.inria.fr/  ********" 1>&2;
-  echo "Do you want this script to try to download and install ocaml"
+  echo "*******  Check http://ocaml.org/  ********" 1>&2;
+  echo "Do you want this script to try to download and install ocaml $REQUIRED_OCAML"
   echo "LOCALLY in mldonkey directory ?"
   if test "$BATCH" = "no"; then read i <&1; else i=yes; fi
   case "$i" in
    y* | Y*)
       cd $PATCH_DIR
-      if [ test "$REQUIRED_OCAML" = "SVN" ]; then
-        rm -rf $BUILD_DIR
-        mkdir -p $BUILD_DIR
-        cd $BUILD_DIR
-        svn checkout http://caml.inria.fr/svn/ocaml/trunk
-        cd trunk
-      else
-        if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          echo Downloading ...
-          $WGET http://caml.inria.fr/pub/distrib/ocaml-"$DOWNLOAD_OCAML_MAJOR"/ocaml-"$REQUIRED_OCAML".tar.gz
-        fi
-        if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          $WGET http://caml.inria.fr/pub/distrib/ocaml-3.11/ocaml-"$REQUIRED_OCAML".tar.gz
-        fi
-        if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          $WGET http://caml.inria.fr/pub/distrib/ocaml-3.10/ocaml-"$REQUIRED_OCAML".tar.gz
-        fi
-        if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          $WGET http://caml.inria.fr/pub/distrib/ocaml-4.00/ocaml-"$REQUIRED_OCAML".tar.gz
-        fi
-        if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          echo "********        download OCaml $REQUIRED_OCAML not successful, try do download it manually       *********" 1>&2;
-          echo "********        from http://caml.inria.fr/pub/distrib/                                   *********" 1>&2;
-          echo "********        and copy the tar.gz into $PATCH_DIR              *********" 1>&2;
-          exit 1
-        fi
+      DOWNLOAD_OCAML_MAJOR=`echo $REQUIRED_OCAML | sed -n -e 's/^\([[0-9]]*\.[[0-9]]*\).*/\1/p'`
+      if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
+        echo Downloading ...
+        $WGET http://caml.inria.fr/pub/distrib/ocaml-"$DOWNLOAD_OCAML_MAJOR"/ocaml-"$REQUIRED_OCAML".tar.gz
+      fi
+      if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
+        $WGET http://caml.inria.fr/pub/distrib/ocaml-4.08/ocaml-4.08.0.tar.gz
+      fi
+      if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
+        echo "********        download OCaml $REQUIRED_OCAML not successful, try do download it manually       *********" 1>&2;
+        echo "********        from http://caml.inria.fr/pub/distrib/                                   *********" 1>&2;
+        echo "********        and copy the tar.gz into $PATCH_DIR              *********" 1>&2;
+        exit 1
+      fi
 
-        echo Uncompressing ...
-        mkdir -p $BUILD_DIR
-        cd $BUILD_DIR
-        rm -rf ocaml-"$REQUIRED_OCAML"
-        gzip -cd $PATCH_DIR/ocaml-"$REQUIRED_OCAML".tar.gz | tar vxf -
-        cd ocaml-"$REQUIRED_OCAML"
-        if test -f $PATCH_DIR/ocaml-"$REQUIRED_OCAML".patch; then
-          echo Patching ...
-          patch -p1 < $PATCH_DIR/ocaml-"$REQUIRED_OCAML".patch
-        fi
+      echo Uncompressing ...
+      mkdir -p $BUILD_DIR
+      cd $BUILD_DIR
+      rm -rf ocaml-"$REQUIRED_OCAML"
+      gzip -cd $PATCH_DIR/ocaml-"$REQUIRED_OCAML".tar.gz | tar vxf -
+      cd ocaml-"$REQUIRED_OCAML"
+      if test -f $PATCH_DIR/ocaml-"$REQUIRED_OCAML".patch; then
+        echo Patching ...
+        patch -p1 < $PATCH_DIR/ocaml-"$REQUIRED_OCAML".patch
       fi
       echo Configuring ...
       ./configure -prefix $LOCAL_DIR -host $host -cc $CC
@@ -682,11 +671,7 @@ if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
         fi
       fi
       cd $BUILD_DIR
-      if [ test "$REQUIRED_OCAML" = "SVN" ]; then
-        rm -rf trunk
-      else
-        rm -rf ocaml-"$REQUIRED_OCAML"
-      fi
+      rm -rf ocaml-"$REQUIRED_OCAML"
       cd $CONFIG_DIR
       echo OCaml locally installed for mldonkey
 
@@ -761,13 +746,11 @@ fi
 
 # force usage of supported OCaml versions
 case "$OCAMLVERSION" in
-    3.10.1*|3.10.2*|3.1*|4.*) ;;
+    3.12*|4.*) ;;
     *)
-      if [ test "$REQUIRED_OCAML" != "SVN" ]; then
-        echo "********  Version $REQUIRED_OCAML of Objective-Caml is required  *********" 1>&2;
-        echo "*******  Check http://caml.inria.fr/  ********" 1>&2;
-        exit 1
-      fi
+      echo "******** OCaml version >= $MINIMUM_OCAML required  *********" 1>&2;
+      echo "*******  Check http://ocaml.org/  ********" 1>&2;
+      exit 1
       ;;
 esac
 
@@ -786,8 +769,8 @@ else
   OCAMLOPTVERSION=`$OCAMLOPT -v | sed -n -e 's|.*version* *\(.*\)$|\1|p' `
 
   test "$OCAMLOPTVERSION" = "$OCAMLVERSION" || {
-    echo "********  Version $REQUIRED_OCAML of ocamlopt is required  *********" 1>&2;
-    echo "*******  Check http://caml.inria.fr/  ********" 1>&2;
+    echo "******** Expected ocamlopt version $OCAMLVERSION , but got $OCAMLOPTVERSION *********" 1>&2;
+    echo "*******  Check http://ocaml.org/  ********" 1>&2;
     exit 1; }
 
   case "$OCAMLVERSION" in
