patch #7795

diff --git a/config/configure.in b/config/configure.in
--- a/config/configure.in
+++ b/config/configure.in
@@ -274,7 +274,7 @@ if test -f ./CVS/Entries ; then
 fi
 
 # **********                                                                                  **********
-# **********             build MLDonkey version, Required Ocaml and LablGTK versions          **********
+# **********             build MLDonkey version, Required OCaml and LablGTK versions          **********
 # **********                                                                                  **********
 
 MLDONKEY_VERSION=$MAJOR_VERSION.$MINOR_VERSION.$SUB_VERSION
@@ -408,10 +408,10 @@ AC_ARG_ENABLE(batch,
   AS_HELP_STRING([--enable-batch], [reply YES to all queries in this script]),
   [BATCH="$enableval"])
 AC_ARG_ENABLE(force-ocaml,
-  AS_HELP_STRING([--enable-force-ocaml], [force usage of self-compiled Ocaml]),
+  AS_HELP_STRING([--enable-force-ocaml], [force usage of self-compiled OCaml]),
   [FORCE_OCAML="$enableval"])
 AC_ARG_ENABLE(ocamlver,
-  AS_HELP_STRING([--enable-ocamlver=VER], [force usage of specific Ocaml version (3.10.1|SVN), ]),
+  AS_HELP_STRING([--enable-ocamlver=VER], [force usage of specific OCaml version (3.10.1|SVN), ]),
   [REQUIRED_OCAML="$enableval"])
 AC_ARG_ENABLE(mingw,
   AS_HELP_STRING([--enable-mingw], [force compilation with MINGW on Cygwin]),
@@ -533,7 +533,7 @@ echo "     Checking system tools finished."
 echo "----------------------------------------"
 echo ""
 echo "--------------------------------"
-echo "     Checking Ocaml compiler."
+echo "     Checking OCaml compiler."
 echo "--------------------------------"
 
 CONFIG_DIR=$SOURCE_DIR/config
@@ -576,18 +576,18 @@ if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
 
   if [ test "$SYSTEM" = "mingw" ]; then
     echo "********         Objective-Caml $REQUIRED_OCAML is required               *********" 1>&2;
-    echo "********     no valid Ocaml compiler found on your system        *********" 1>&2;
+    echo "********     no valid OCaml compiler found on your system        *********" 1>&2;
     echo "********   on MinGW there is no possibility to let configure     *********" 1>&2;
-    echo "********   build the Ocaml compiler with the included script     *********" 1>&2;
+    echo "********   build the OCaml compiler with the included script     *********" 1>&2;
     echo "********    check http://mldonkey.sourceforge.net/Windows        *********" 1>&2;
-    echo "********   for instuctions how to compile Ocaml under MinGW      *********" 1>&2;
+    echo "********   for instuctions how to compile OCaml under MinGW      *********" 1>&2;
     exit 1
   else  
     
   echo "********  Objective-Caml $REQUIRED_OCAML is required  *********" 1>&2;
   if [ test "$WGET" = "" ] && [ test "$REQUIRED_OCAML" != "SVN" ]; then
     echo "********          wget is missing          *********" 1>&2;
-    echo "********       cannot download Ocaml       *********" 1>&2;
+    echo "********       cannot download OCaml       *********" 1>&2;
     exit 1
   fi
   echo "*******  Check http://caml.inria.fr/  ********" 1>&2;
@@ -615,7 +615,7 @@ if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
           $WGET http://caml.inria.fr/pub/distrib/ocaml-3.10/ocaml-"$REQUIRED_OCAML".tar.gz
         fi
         if test ! -f ocaml-"$REQUIRED_OCAML".tar.gz; then
-          echo "********        download Ocaml $REQUIRED_OCAML not successful, try do download it manually       *********" 1>&2;
+          echo "********        download OCaml $REQUIRED_OCAML not successful, try do download it manually       *********" 1>&2;
           echo "********        from http://caml.inria.fr/pub/distrib/                                   *********" 1>&2;
           echo "********        and copy the tar.gz into $PATCH_DIR              *********" 1>&2;
           exit 1
@@ -655,7 +655,7 @@ if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
         rm -rf ocaml-"$REQUIRED_OCAML"
       fi
       cd $CONFIG_DIR
-      echo Ocaml locally installed for mldonkey
+      echo OCaml locally installed for mldonkey
 
       if test -f "$LOCAL_OCAML"/ocamlc.opt; then
          OCAMLC=$LOCAL_OCAML/ocamlc.opt
@@ -665,7 +665,7 @@ if [ test "$BUILD_OCAML" = "yes" ] || [ test "$FORCE_OCAML" = "yes" ]; then
          OCAMLC=$LOCAL_OCAML/ocamlc
          ac_cv_prog_OCAMLC=$LOCAL_OCAML/ocamlc
       else
-        echo "Ocaml installation failed"; exit 1
+        echo "OCaml installation failed"; exit 1
       fi
       fi
       ;;
@@ -726,7 +726,7 @@ if test -f $OCAMLLIB/dynlink.cmxa; then
   CAMLP4LIB_OPT="dynlink.cmxa $CAMLP4LIB_OPT"
 fi
 
-# force usage of supported Ocaml versions
+# force usage of supported OCaml versions
 case "$OCAMLVERSION" in
     3.10.1*|3.10.2*|3.1*) ;;
     *)
@@ -755,7 +755,7 @@ else
 fi
 
 echo "-------------------------------------------"
-echo "     Checking Ocaml $OCAMLVERSION finished."
+echo "     Checking OCaml $OCAMLVERSION finished."
 echo "-------------------------------------------"
 
 
@@ -1747,7 +1747,7 @@ if test "$TARGET_TYPE" = "byte"; then
 fi
 echo ""
 printf "Compilers:"
-echo " - Ocaml version     $OCAMLVERSION $OCAML_TYPE"
+echo " - OCaml version     $OCAMLVERSION $OCAML_TYPE"
 echo " - $CC version       $CC_VERSION"
 if test "x$CXX" != "x"; then
   echo " - $CXX version       $CXX_VERSION"
