-

diff --git a/config/configure.in b/config/configure.in
--- a/config/configure.in
+++ b/config/configure.in
@@ -11,7 +11,7 @@ MYCONFIG_ARGS_DEFINED=yes
 echo $MYCONFIG_ARGS
 
 CURRENT_VERSION=2.5
-CURRENT_RELEASE=30.8
+CURRENT_RELEASE=30.9
 if test -d .svn; then
   CURRENT_RELEASE=${CURRENT_RELEASE}_r`svnversion -n .`
 fi
@@ -55,13 +55,13 @@ DEBUG=no
 SWARMING1=no
 
 MULTINET=yes
-AC_ARG_ENABLE(multinet,      [  --disable-multinet:       allows you to only compile support for edonkey + Overnet], [MULTINET="$enableval"])
+AC_ARG_ENABLE(multinet,      [  --disable-multinet:     allows you to only compile support for edonkey + Overnet], [MULTINET="$enableval"])
 
-AC_ARG_ENABLE(newgui, [  --disable-newgui:         allows you to compile the old-gui], [BUILD_NEWGUI="$enableval"])
+AC_ARG_ENABLE(newgui, [  --disable-newgui:       allows you to compile the old-gui], [BUILD_NEWGUI="$enableval"])
 
 AC_ARG_ENABLE(mingw, [  --enable-mingw:         forces compilation with MINGW on Cygwin], [FORCE_MINGW="$enableval"])
 
-AC_ARG_ENABLE(checks, [  --enable-checks:          force mldonkey to perform bound checks on array/string access], [CHECKBOUNDS="$enableval"])
+AC_ARG_ENABLE(checks, [  --enable-checks:        force mldonkey to perform bound checks on array/string access], [CHECKBOUNDS="$enableval"])
 
 if test "$CHECKBOUNDS" = "yes"; then
   CHECKBOUNDS=true
@@ -86,53 +86,55 @@ if test ! "$MULTINET" = "yes"; then
   BROOSNET=no
 fi
 
-AC_ARG_ENABLE(batch, [  --enable-batch:           reply YES to all queries in this script], [BATCH="$enableval"])
+AC_ARG_ENABLE(batch, [  --enable-batch:         reply YES to all queries in this script], [BATCH="$enableval"])
 
-AC_ARG_ENABLE(gui,           [  --disable-gui:            allows you to remove the GUI], [BUILD_GUI="$enableval"])
+AC_ARG_ENABLE(gui,           [  --disable-gui:          allows you to remove the GUI], [BUILD_GUI="$enableval"])
 
-AC_ARG_ENABLE(donkey,        [  --disable-donkey:         allows you to remove support for eDonkey], [DONKEY="$enableval"])
+AC_ARG_ENABLE(donkey,        [  --disable-donkey:       allows you to remove support for eDonkey], [DONKEY="$enableval"])
 
-AC_ARG_ENABLE(bittorrent,    [  --disable-bittorrent:     allows you to remove support for Bittorent], [BITTORRENT="$enableval"])
+AC_ARG_ENABLE(bittorrent,    [  --disable-bittorrent:   allows you to remove support for Bittorent], [BITTORRENT="$enableval"])
 
-AC_ARG_ENABLE(filetp,        [  --disable-filetp:         allows you to remove support for fileTP], [FILETP="$enableval"])
+AC_ARG_ENABLE(filetp,        [  --disable-filetp:       allows you to remove support for fileTP], [FILETP="$enableval"])
 
-AC_ARG_ENABLE(gnutella, [  --disable-gnutella:       allows you to remove support for Gnutella], [GNUTELLA="$enableval"])
+AC_ARG_ENABLE(gnutella, [  --disable-gnutella:     allows you to remove support for Gnutella], [GNUTELLA="$enableval"])
 
-AC_ARG_ENABLE(gnutella2, [  --disable-gnutella2:      allows you to remove support for Gnutella2], [GNUTELLA2="$enableval"])
+AC_ARG_ENABLE(gnutella2, [  --disable-gnutella2:    allows you to remove support for Gnutella2], [GNUTELLA2="$enableval"])
 
-AC_ARG_ENABLE(soulseek, [  --disable-soulseek:       allows you to remove support for SoulSeek], [SOULSEEK="$enableval"])
+AC_ARG_ENABLE(soulseek, [  --disable-soulseek:     allows you to remove support for SoulSeek], [SOULSEEK="$enableval"])
 
-AC_ARG_ENABLE(fasttrack,     [  --disable-fasttrack:      allows you to remove support for FastTrack], [FASTTRACK="$enableval"])
+AC_ARG_ENABLE(fasttrack,     [  --disable-fasttrack:    allows you to remove support for FastTrack], [FASTTRACK="$enableval"])
 
-AC_ARG_ENABLE(opennap,       [  --disable-opennap:        allows you to remove support for Open Napster], [OPEN_NAPSTER="$enableval"])
+AC_ARG_ENABLE(opennap,       [  --disable-opennap:      allows you to remove support for Open Napster], [OPEN_NAPSTER="$enableval"])
 
-#AC_ARG_ENABLE(directconnect, [  --disable-directconnect:  allows you to remove support for Direct Connect], [DIRECT_CONNECT="$enableval"])
+#AC_ARG_ENABLE(directconnect, [  --disable-directconnect: allows you to remove support for Direct Connect], [DIRECT_CONNECT="$enableval"])
 
-#AC_ARG_ENABLE(audiogalaxy,   [  --disable-audiogalaxy:    allows you to remove support for Audio Galaxy], [AUDIO_GALAXY="$enableval"])
+#AC_ARG_ENABLE(audiogalaxy,   [  --disable-audiogalaxy:  allows you to remove support for Audio Galaxy], [AUDIO_GALAXY="$enableval"])
 
-AC_ARG_ENABLE(openft,        [  --disable-openft:         allows you to remove support for OpenFT], [OPENFT="$enableval"])
+AC_ARG_ENABLE(openft,        [  --disable-openft:       allows you to remove support for OpenFT], [OPENFT="$enableval"])
 
-AC_ARG_ENABLE(ares,     [  --disable-ares:      allows you to remove support for Ares], [ARES="$enableval"])
+AC_ARG_ENABLE(ares,     [  --disable-ares:         allows you to remove support for Ares], [ARES="$enableval"])
 
-AC_ARG_ENABLE(cymes,         [  --disable-cymes:          allows you to remove support for Cymes], [CYMES="$enableval"])
+AC_ARG_ENABLE(cymes,         [  --disable-cymes:        allows you to remove support for Cymes], [CYMES="$enableval"])
 
-AC_ARG_ENABLE(ocamlver, [  --enable-ocamlver=3.08.0:   allows you to change the required version of ocaml], [REQUIRED_OCAML="$enableval"])
+AC_ARG_ENABLE(ocamlver, [  --enable-ocamlver=VER:  allows you to change the required version of ocaml to VER], [REQUIRED_OCAML="$enableval"])
 
-AC_ARG_ENABLE(gtk2, [  --enable-gtk2:   allows you to compile using GTK2], [USE_GTK2="$enableval"])
+AC_ARG_ENABLE(gtk2, [  --enable-gtk2:          allows you to compile using GTK2], [USE_GTK2="$enableval"])
 
 
 PTHREAD_LIBS=yes
-AC_ARG_ENABLE(pthread, [  --disable-pthread :        allows you to disable pthread support in mldonkey], [PTHREAD_LIBS="$enableval"])
-AC_ARG_ENABLE(pthread-lib, [  --enable-pthread-lib :    legacy option], [PTHREAD_LIBS="$enableval"])
+AC_ARG_ENABLE(pthread, [  --disable-pthread:      allows you to disable pthread support in mldonkey], [PTHREAD_LIBS="$enableval"])
+AC_ARG_ENABLE(pthread-lib, [  --enable-pthread-lib:   legacy option], [PTHREAD_LIBS="$enableval"])
 
+ICONV=yes
+AC_ARG_ENABLE(iconv,       [  --disable-iconv:        disable the use of iconv for compiling on broken windows environments], [ICONV="enableval"])
 
-AC_ARG_ENABLE(profile, [  --enable-profile:   allows you to profile mlnet using gprof], [PROFILE="$enableval"])
+AC_ARG_ENABLE(profile, [  --enable-profile:       allows you to profile mlnet using gprof], [PROFILE="$enableval"])
 
-AC_ARG_ENABLE(debug, [  --enable-debug:   allows you to compile mlnet with debug symbols], [DEBUG="$enableval"])
+AC_ARG_ENABLE(debug, [  --enable-debug:         allows you to compile mlnet with debug symbols], [DEBUG="$enableval"])
 
 
 IM=yes
-AC_ARG_ENABLE(devel, [  --enable-devel:           (undocumented)], [DEVEL="$enableval"])
+AC_ARG_ENABLE(devel, [  --enable-devel:         (undocumented)], [DEVEL="$enableval"])
 
 ifelse(AC_ACVERSION, [2.13], [],
 [dnl Large file enabled
@@ -140,7 +142,7 @@ ifelse(AC_ACVERSION, [2.13], [],
 
 ])
 
-AC_ARG_ENABLE(swarming1, [  --enable-swarming1:           very experimental], [SWARMING1="$enableval"])
+AC_ARG_ENABLE(swarming1, [  --enable-swarming1:     depricated (don't use it)], [SWARMING1="$enableval"])
 
 AC_CANONICAL_HOST
 AC_CHECK_PROG(CC,gcc3,"gcc3",cc)
@@ -166,7 +168,7 @@ PATCH_DIR=$SOURCE_DIR/patches
 LOCAL_DIR=$PATCH_DIR/local
 BUILD_DIR=$PATCH_DIR/build
 
-AC_ARG_ENABLE(local-prefix, [--enable-local-prefix=prefix:           allows you to specify where you want temporary tools to be installed (prefix must be absolute)], [LOCAL_DIR="$enableval"])
+AC_ARG_ENABLE(local-prefix, [  --enable-local-prefix=DIR: allows you to specify where you want temporary tools to be installed (DIR must be absolute)], [LOCAL_DIR="$enableval"])
 
 LOCAL=$LOCAL_DIR
 LOCAL_OCAML=$LOCAL_DIR/bin
@@ -487,36 +489,22 @@ AC_CHECK_HEADERS(endian.h byteswap.h,,[
     SHA1_VERSION=sha1old
     ])
 
-AM_ICONV
-if test "$am_cv_func_iconv" != "yes"; then
-  echo "iconv() is missing, did you install the libraries and the developer packages for libiconv?"
-  exit 1
+if test "$ICONV" = "yes"; then
+  AM_ICONV
+  if test "$am_cv_func_iconv" != "yes"; then
+    echo "iconv() is missing, did you install the libraries and the developer packages for libiconv?"
+    exit 1
+  fi
+  LIBS="$LIBS $LIBICONV"
+  AC_CHECK_FUNCS([locale_charset])
+  AC_CHECK_HEADERS([libcharset.h])
+  AC_CHECK_HEADERS([locale.h])
+  AC_CHECK_LIB(charset,locale_charset)
+  case $host in *freebsd*|*openbsd*) CONFIG_INCLUDES="$CONFIG_INCLUDES -I /usr/local/include";; esac
+else
+  AC_DEFINE(DISABLE_ICONV, 1, [Define to 1 if you want to replace iconv and related with stubs.])
 fi
 
-case $host in
-        *freebsd*|*openbsd*)
-	   LIBS="$LIBS $LIBICONV"
-	   AC_CHECK_FUNCS([locale_charset],,AC_MSG_ERROR([locale_charset is missing]))
-	   AC_CHECK_HEADERS([libcharset.h])
-           CONFIG_INCLUDES="$CONFIG_INCLUDES -I /usr/local/include"
-        ;; 
-        *)
-	   HAVE_LOCALE_CHARSET=no
-	   if test -n "$LIBICONV"; then
-	     AC_CHECK_LIB(charset,locale_charset,[HAVE_LOCALE_CHARSET=yes])
-	     if test "$HAVE_LOCALE_CHARSET" = "no"; then
-	       echo "libcharset is missing, it is part of the libiconv library."
-	       echo "Did you install the libraries and the developer packages?"
-	       echo "Check libiconv is in your path."
-	       exit 1
-	     else
-	       AC_CHECK_HEADERS(libcharset.h,,)
-	       AC_DEFINE(HAVE_LOCALE_CHARSET, 1, [Define if you have libcharset with the locale_charset() function.])
-	       LIBICONV="$LIBICONV -lcharset"
-	     fi
-	   fi
-        ;;
-esac
 
 # On linux plaforms, we will have to check that includes from kernel are
 # available.
